services:
  dev:
    build:
      context: .
      args:
        UBUNTU_VERSION: 24.04
        LEFTHOOK_VERSION: 2.1.9
        GITLEAKS_VERSION: 8.30.1
        GOLANG_VERSION: 1.26.4
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - type: bind
        source: ..
        target: /workspace
        consistency: cached
      - type: bind
        source: .bash
        target: /home/vscode/.bash
        consistency: delegated
    environment:
      TZ: Asia/Tokyo
